### The following is the "svc.yml" file used in the module
apiVersion: v1
kind: Service
metadata:
  name: bookstore-svc
  labels:
    app: bookstore-svc
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30001
    protocol: TCP
  selector:
    app: bookstore-app