---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bookstore-deploy
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        name: bookstoreapp
    spec:
      containers:
      - name: bookstoreapp
        image: imjayakumar/bookstoreapp
        ports:
        - containerPort: 3000
