---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-deploy
spec:
  template:
    metadata:
      labels:
        name: mongodb
    spec:
      containers:
        -
          image: mongo
          name: mongodb
          ports:
            -
              containerPort: 27017
